### ISSUE TITLE
Reconsider Adobe Spectrum?

### ISSUE THREAD

**Issue by richardolsson** [zetkin/app.zetkin.org#148]
Having recently started implementing more complex UI using Spectrum, we've run into some issues. Let's collect concerns here, and then reevaluate whether we should stick with Spectrum or migrate ASAP to something else.

**Comment by richardolsson** [comment]
Please share your thoughts here going forward, @nehahirve

**Comment by nehahirve** [comment]
The biggest hurdle I'm having so far is that it doesn't seem to obviously enable media queries, or custom layout changes depending on the screen width.

**Comment by nehahirve** [comment]
I am using <ul> and <li> elements instead of ListBox for a list of links, since I can’t make it work with links — that component doesn’t seem to be designed for a list of links, rather a list of options that can be selected.

Doesn't seem to have a separate List component, or if it's needed.

**Comment by nehahirve** [comment]
The search drawer is proving difficult to implement using the out of the box spectrum components -- they provide us with Dialog and DialogContainers for overlays, which is 1. not really what the search drawer is, and b. is  limited in terms of positioning

**Comment by richardolsson** [comment]
Accidental close, sorry!

**Comment by nehahirve** [comment]
difficult to test layout things in unit tests. Cannot find any documentation or plugins or discussion as to how to integrate spectrum w/ Cypress for unit testing, ended up using inline styles to test DOM layout

**Comment by kristofferlarberg** [comment]
The `Tabs` component does not make possible displaying content above the tab options, which would have been perfect in terms of the UI for `/my*`. The component only allows for display below and to the right and is not something that seemed possible to quickly modify. However, there is a new version (release candidate) out now, which has a slightly different structure.

Another thing that would need to be modified if using `Tabs` is how it collapses into a `Picker` when there is not enough vw.

**Comment by kristofferlarberg** [comment]
The `Button` offers five different variations. These variations mainly entail different colors and can be used with the `isQuiet` prop which removes border and background color (only shown on `hover`). In my opinion this is too limited and would have been great with an easy way of changing for instance `border-radius` and `padding` in other ways than regular css.

The structure in general is very solid, which is a good thing if you don't need to many custom modifications. In terms of responsiveness it's as mentioned above tricky to make custom variations. It would have been optimal to be able to decide sizing for certain elements at different screen widths, but maybe also to be able to change certain component props when width changes.

Adding your own color to an element doesn't go so well with the dark/light mode functionality of the theme (which otherwise is quite nice) since the custom color wont change with the theme switching between dark/light (is there an easy way of achieving this?).

Here's a demo of `/my*` that I did after doing some quick fixes I did before handing in the degree project for review:
https://www.dropbox.com/s/sxpj3ptlwx07rw4/zetkin-mypage-demo-720.mov?dl=0

**Comment by nehahirve** [comment]
The action button does not have a way to add padding -- it provides correct padding when i pass in a string directly but not when I put in a Msg component

**Comment by richardolsson** [comment]
I've created issues #192 and #193 to test Material UI as an alternative in two different scenarios.

**Comment by richardolsson** [comment]
This rich-text editor for Material UI seems really nice: https://github.com/niuware/mui-rte

**Comment by richardolsson** [comment]
We decided to migrate to MUI.
