### ISSUE TITLE
Implement "is any of" filter in lists

### ISSUE THREAD

**Issue by ziggabyte** [zetkin/app.zetkin.org#1544]
## Description
Attempting to apply the "is any of" operator when filtering a list creates an error, and the UI does not match other inputs in the filter modal.

## Steps to reproduce
1. Go to a list
2. Click on "Filter"
3A. In "operator" dropdown, select "any of"
3B. Type something into the text input, and "enter" to apply filter

### Expected Behaviour
3A - the text input has the same look as the other text inputs in the filter modal
3B - the list gets filtered by any of the things that has been typed into the text input

### Actual Behaviour
3A - it has the outlined style, not the "standard"
3B - attempting to apply this filter causes an error 

## Screenshots (if you have any)
![bild](https://github.com/zetkin/app.zetkin.org/assets/58265097/98bbb91a-31c9-4c25-a51b-d335509f6f7b)
![bild](https://github.com/zetkin/app.zetkin.org/assets/58265097/33fe99ba-80c0-4043-85e0-580030f97d6f)

**Comment by niklasva82** [comment]
The problem appears to occur in the `GridFilterInputMultipleValue` in the mui-x-data-grid package. The item value provided is a string while the component expects an array of mutliple strings to filter on. It should be noted that this is not the case the first time this code is run, so the value of the item is somehow updated to a string rather than an array of the string.

![Screenshot from 2023-09-20 23-52-46](https://github.com/zetkin/app.zetkin.org/assets/14962107/6dec182a-e352-46db-a635-e28b6fde10b4)

**Comment by niklasva82** [comment]
I'm wondering if perhaps this is a bug that has been solved in v6. Will have to check out #1500

**Comment by niklasva82** [comment]
I will either try to override the problematic function tomorrow or I will disable the functionality altogether. Migrating to v6 did not help.
