### ISSUE TITLE
Menu to create event by dragging in weekly calendar appears in header.

### ISSUE THREAD

**Issue by ziggabyte** [zetkin/app.zetkin.org#1574]
## Description
My screen is small so when creating an event by dragging in the weekly calendar, the point where i began dragging scrolls out of view. When i release to create the event the little menu appears up in the header, not inside the calendar. It looks confusing.

## Steps to reproduce
1. Go to the weekly calendar
2. If you have a large screen, zoom to make it behave smaller
3. Begin to create an event by clicking and dragging, and drag until the beginning of the event has scrolled out of view
4. Release to create the event

### Expected Behaviour
The menu with options to create the event appears inside the weekly calendar

### Actual Behaviour
The menu with options to create the event appears up in the header

## Screenshots (if you have any)
![bild](https://github.com/zetkin/app.zetkin.org/assets/58265097/d3743bb3-23f4-45c2-b7d5-11e72e0feafd)

**Comment by troldmand** [comment]
Hi @ziggabyte , I can't reproduce in Chrome: 
![Screenshot 2023-11-09 at 18 11 51](https://github.com/zetkin/app.zetkin.org/assets/9819978/6db6bd3f-09f6-4f95-b574-0ed8dcb88630)

Which browser did you have the experience in?

**Comment by richardolsson** [comment]
@troldmand: I'm guessing that it's Firefox, and that it's easier to reproduce on screens that are very small on the vertical axis.

**Comment by troldmand** [comment]
Will try Safari and Firefox :) I use responsive mode to try out many different possible sizes.

**Comment by richardolsson** [comment]
> Will try Safari and Firefox :) I use responsive mode to try out many different possible sizes.

Cool! I would avoid responsive mode (and instead just resize the entire window) because the responsive mode may affect how mouse interactions are handled by the browser, and I believe this will only happen when you start dragging and drag so far down that the top of the event you're creating scrolls out of view.

**Comment by troldmand** [comment]
Ah! I see it! And I can also reproduce it in Chrome. 

![Screenshot 2023-11-09 at 18 26 35](https://github.com/zetkin/app.zetkin.org/assets/9819978/2b032bae-bcd3-4e15-b5b0-4871cf33bfea)

I see what's happening. The 'option to create' pop-up label will always appear at the top of a newly created event - even if you start dragging a new event, **then scroll down inside the calender**, then release to have the pop-up show: And there you have it. The label still appears at the top of the event, but by now, that 'top' is outside of the view of the calender (because you scrolled while creating). 

![Large GIF (380x672)](https://github.com/zetkin/app.zetkin.org/assets/9819978/b132183d-dcf1-497f-93c0-d222f0b340fc)

Could be nice to find a solution that still allows for scrolling while creating an event, I guess. 

Hmm.

**Comment by troldmand** [comment]
Yay, I opened a PR for a fix! Please ATTACK it with all your might.
