### ISSUE TITLE
Fix display of "Extra data" in lists

### ISSUE THREAD

**Issue by rebecarubio** [zetkin/app.zetkin.org#1590]
## Description
When I chose to add a custom field called "Extra data" to my list it renders the object instead of the value

## Steps to reproduce
1. Go to 'http://app.dev.zetkin.org/organize/1/people/views/112'
2. See how the Custom Field column "Extra data" doesn't render the value.

### Expected Behaviour
Extra data column displays the human readable value

### Actual Behaviour
Extra data column displays the object

## Screenshots (if you have any)

![Image](https://github.com/zetkin/app.zetkin.org/assets/36491300/d25e657d-8a7c-4a9f-b77c-053f3e3bdeb2)

**Comment by richardolsson** [comment]
The value actually is an object. That field is of type `json`, and the data stored in it is an arbitrary JSON blob, i.e. an object. So the bug here is not that it's displaying an object, but that it's displaying the object using the default `toString()` which returns [object Object].

I think the solution to this is really to disable this type of fields from being added as columns. If we allow them to be added, we need to come up with a nice way of rendering such objects. I guess rendering them using `JSON.stringify()` is another viable option.

I'm not sure which is better?

**Comment by rebecarubio** [comment]
Not sure also what's better... I guess if we have the functionality ready and it's a matter of just rendering using stringify() it's better to fix it than to disable them? But I', also unsure how much they are used.

**Comment by richardolsson** [comment]
Ok! Let's just print with `JSON.stringify()`. This is a very rare field to use, so I think that's a good enough solution.

**Comment by richardolsson** [comment]
Having thought some more about this, I'm back at thinking we should disable them from being added as columns in a list. This type of field is intended for data required by integrations, i.e. to store some arbitrary data on a person in order to tie them together with a record in some external database or something like that. They should never really be visible to users, and I believe we hide them in all other places.

**Comment by annikalindberg** [comment]
I dont know the codebase that well still, where is the "lists" rendered from? I cant seam to localize them
