### ISSUE TITLE
Redirection to page full of json after login

### ISSUE THREAD

**Issue by kristofferlarberg** [zetkin/app.zetkin.org#183]
This has happened after login. It's not clear if it still occurs nor if it depends on the page visited previous to logging in.

1. Login (possibly after being idle and session running out on `/my*`)

Expected result: Redirection to previously visited page or `/`
Actual result:
![Skärmavbild 2021-05-14 kl  10 33 08](https://user-images.githubusercontent.com/51208557/118992713-29eb2f80-b985-11eb-868a-9f1a18e05764.png)

**Comment by richardolsson** [comment]
I have seen this (and similar issues) occur and my assumption has been that it happens because react-query or NEXT tries to load the json file, at which point the back-end detects that the user is no longer logged, in and redirects to login. Because the last request before login was to this JSON file, that's what's stored in the `redirectAfterLogin` session variable, so that's where the user is redirected to after logging in.

If that's the case, it should be possible to reproduce this issue by navigating manually to the JSON URL without logging in, but that doesn't seem to happen for me.

It would have been useful to see the full JSON that was being returned in this error. If anyone comes across it, please post the full JSON response.

**Comment by richardolsson** [comment]
Another hypothesis for a potential series of events that might be causing this:

1. Token expires
2. More than one request is made in parallel
3. Request 0 fails and initiates a token refresh
4. Request 1 fails and initiates a token refresh
5. Request 0 refresh completes and tokens are replaced (refresh token invalidated)
6. Request 1 refresh fails, because the refresh token is no longer valid
7. Because request 1 has failed with 401, scaffold redirects to login

**Comment by nehahirve** [comment]
I've added some console logs and confirmed that `req.url` is sometimes the .json url, which gets stored in redirAfterLogin

Reproduce by deleting the `sid` cookie and navigating to another page.

The json returned is the query data from getServerSideProps -- full json in slack
