### ISSUE TITLE
Runtime error when adding or removing contact person for event after refreshing page

### ISSUE THREAD

**Issue by MattettaM** [zetkin/app.zetkin.org#1849]
## Description
When adding or removing a contact person after refreshing an event page it triggers a unhandled runtime error in store.ts

## Steps to reproduce
1. Go to any Event Page.
2. Go to Participants.
3. Refresh the page.
4. Click on 'Select a contact person'
5. Search for a person to add and add that person.
6. Error
7. Refresh page again. (Contact person has been added)
8. Remove the contact person
9. Error
10. Refresh page. (Contact person has been removed)

### Expected Behaviour
Adding or removing the contact person should be performed without triggering an error.

### Actual Behaviour
Adding or removing a contact person triggers an error and performs the action.

## Screenshots (if you have any)
![image](https://github.com/zetkin/app.zetkin.org/assets/14234034/98a12899-1aa8-4675-9504-dfce4289c239)
![image](https://github.com/zetkin/app.zetkin.org/assets/14234034/26e3e9fb-db5b-4c31-9038-e2c86e2eb6ad)

**Comment by richardolsson** [comment]
I think this is because events are not added to the `eventsByCampaignId` part of the state when navigating directly to an event page and loading a single event. This is just a guess, but if it's true, the fix should be to make sure the `eventLoaded` reducer puts the event in `state.eventsByCampaignId`.
