### ISSUE TITLE
Email: tab no longer opens block menu (in editor)

### ISSUE THREAD

**Issue by ziggabyte** [zetkin/app.zetkin.org#1908]
**Please be as thorough as possible, but if you can't answer everything, please just submit what you have! Thank you!**

## Description
The tab key used to be what opened the block menu, for easy keyboard navigation and adding blocks. Since the introduction of tabs in the sidebar, those tabs "steal" the keypress of the tab key. 

## Steps to reproduce
1. Go to the email editor in an email
2. when in the editor, press tab key

### Expected Behaviour
opens editor block menu

### Actual Behaviour
focuses the first tab in the sidebar

## solution
either look at how to "keep" the tab press in the editor, or just create a different shortcut for opening the block menu.

**Comment by ziggabyte** [comment]
According to this: https://github.com/codex-team/editor.js/pull/2569 using tab key to open toolbar is updated in a late december release of Editorjs. Instead it uses `/` to open toolbar. 

From what I can gather, in earlier versions of Editorjs there is no openly offered method to override the keyboard shortcut that opens the toolbar. I did find this "hack" to do it on your own, but I am skeptical if this is a stable long-term solution: https://github.com/codex-team/editor.js/issues/927#issuecomment-1845382620

**Comment by henrycatalinismith** [comment]
This issue was fixed in https://github.com/zetkin/app.zetkin.org/pull/1916, a couple of weeks after it was created. As part of that pull request, @editorjs/editorjs got upgraded to [2.29.0](https://github.com/codex-team/editor.js/blob/next/docs/CHANGELOG.md#2290), which includes the new `/` shortcut.

<img src="https://github.com/user-attachments/assets/cece31e8-99e5-46d7-b23c-7283a01d28de" width="555" />

Dunno why the menu sits slightly outside the visible area like that. Doesn't happen for me when I run it locally, but on https://app.dev.zetkin.org/organize/1/projects/13/emails/28/compose it does glitch a bit with the positioning for some reason.

I think `/` is better than using tab for this. Two reasons.

1. It's become popularised by software like Notion.
2. Tab is already taken for focus management.

Clobbering the tab key to trigger this menu would introduce an obstacle where it becomes more difficult or impossible for keyboard-only users to compose and send emails. There's a workaround that's fairly commonplace – setting up Ctrl+M to toggle between the two different modes for the tab key – but given the rise of the / key as the de-facto standard for triggering these rich text editor block menu popups it's extra steps for an arguably less intuitive UX. I reckon just keep it as -is!

**Comment by richardolsson** [comment]
Yeah, you're right @henrycatalinismith. Let's not make any changes to this behavior.
