### ISSUE TITLE
Smart search: Cannot select number in "at least" option in tags filter

### ISSUE THREAD

**Issue by ziggabyte** [zetkin/app.zetkin.org#1930]
## Description
I can't seem to select a number in the number selector in the tags filter, when selecting "at least" version of the filter. 

## Steps to reproduce
1. Go to somewhere with a smart search dialog
2. Select to add/remove people, and select "Based on tags"
3. Select "at least" from the dropdown
4. Attempt to edit the number 

### Expected Behaviour
I can edit the number either from clicking the field and then using the keyboard for deleting the existing number and typing in a new one, or by using the little up/down arrow buttons to increase or decrease the number

### Actual Behaviour
I cannot use the up/down arrow buttons, and when I attempt to delete the existing number to type in a new one, the filter changes and I cannot change back to the "at least" version. 

## Screenshots (if you have any)

https://github.com/zetkin/app.zetkin.org/assets/58265097/9c6f1a4e-2edd-4882-8733-b1ff1f6515ff

**Comment by awarn** [comment]
Jumping on this

**Comment by awarn** [comment]
Two different problems, with a third bigger one underneath:
1. Not being able to increase the number is just because there have been no tags selected yet, and the number field has a maximum attribute bounded by that. So mostly a UX issue. Simple solution is to just allow any number to be entered here, not sure we need the upper bound. Or you can max out at the maximum selectable amount of tags, maybe.
2. Deleting the number causing a reset to `any` is caused by a definition loop where having a value in the number field is seen as the setting keeping the form in the `min_matching` state (looks like we're trying to not mess with the `CONDITION_OPERATOR` enum, because that touches on a handful of unrelated uses). But, of course, when you then delete that number value, the form reverts to the default `any` state.
3. The promised third, bigger, problem is that I am not sure this filter even works correctly. Regardless of the `min_matching` value,  the filter still seems to just work like the `any` condition.
