### ISSUE TITLE
List: Editing tag value adds a new tag

### ISSUE THREAD

**Issue by kaulfield23** [zetkin/app.zetkin.org#1952]
## Description
When I edit a tag value in a list column, I expect it to be edited, but instead, it adds a new tag with the edited value while the previous value remains unchanged.
## Steps to reproduce
1. Go to any list.
2. Click on '+New column'
3. Click on 'Tag' in 'Categorizing' section
4. Click on '+Add tag'
5. Click on a tag with value. For example 'Paid amount'
6. Click on 'add 1 column'
7. Give any value to the tag
8. Change the value again by double clicking the cell
9. Check the tag in person's card by hovering on avatar

### Expected Behaviour
The value should be changed
### Actual Behaviour
Adds a new tag with a new value. Previous value still remains.
## Screenshots (if you have any)

https://github.com/zetkin/app.zetkin.org/assets/77925373/f2e95a16-2566-4621-b5a2-1e8d9ba1791e

**Comment by richardolsson** [comment]
I doubt that this has anything to do with the backend. I'm assuming that refreshing the page and hovering the same person will render the tag only once, with the most recent value. More likely this is the cache (store) not being updated correctly because we haven't had this situation before where a tag value gets updated, only added, and the store probably contains no logic to remove (or change) the old tag before adding the new one.
