### ISSUE TITLE
Survey submissions show up in wrong survey

### ISSUE THREAD

**Issue by richardolsson** [zetkin/app.zetkin.org#1958]
## Description
When navigating around between surveys, without ever refreshing the page, there seems to be something wrong with the cache that is causing submissions to be rendered in the list for the wrong survey.

## Steps to reproduce
1. Go to "My very open survey" at https://app.dev.zetkin.org/organize/1/projects/standalone/surveys/1/submissions
2. Note the survey submissions in the list
3. Click on "Projects" in the breadcrumbs
4. Click on the "Activities" tab
5. Find any survey other than "My very open survey" and click on it
6. Click the "Submissions" tab

### Expected Behaviour
The list should contain other submissions than the one listed in step 2.

### Actual Behaviour
The list is identical to the one in step 2, showing submissions of another survey than the one we are visiting. Refreshing the page shows the correct results.

### Original survey
![image](https://github.com/zetkin/app.zetkin.org/assets/550212/b11bc7f0-1824-44da-a4bf-e66536016522)

### Another survey (showing same submissions)
![image](https://github.com/zetkin/app.zetkin.org/assets/550212/12256464-f521-4c5e-8eaf-f45d74224b42)

**Comment by richardolsson** [comment]
This must be a bug with how data is cached in the store. When submissions have already been loaded in one survey, visiting the submissions list for another survey does not trigger submissions to be loaded anew, but just uses the same cached list.

Without having looked at this yet, I would recommend that whoever takes this on starts by looking at the structure of the survey store. Submissions should be stored per survey (e.g. `submissionsBySurveyId`). It makes no sense to have a single submissions list.

**Comment by henrycatalinismith** [comment]
Continuing to focus on mopping up survey issues ahead of the big merge. Best to provide a nice clear landing zone for that thing. So I've been investigating your suggested fix here and there's even a `// TODO: Segregate submission content from submission list` just like your comment.

From there I've been looking at everything that either reads from or writes to `submissionList`. Each such place will need updating. Each one will now need a survey ID, and in some cases this will mean changing call signatures for store actions, hooks, and maybe components too. Nothing unusual here, just me mapping out the solution verbally.

I wanted to get a real clear understanding of the layout of these relationships before even beginning to code. So here's a flow diagram representing the network of relationships between everything connected to the `submissionList` property in the survey slice.

```mermaid
flowchart LR

  subgraph store
    subgraph state
      submissionList
    end

    subgraph actions
      submissionLoad
      submissionLoaded
      surveySubmissionUpdate
      surveySubmissionUpdated
      surveySubmissionsLoad
      surveySubmissionsLoaded
    end
  end

  submissionLoad --> submissionList
  submissionLoaded --> submissionList
  surveySubmissionUpdate --> submissionList
  surveySubmissionUpdated --> submissionList
  surveySubmissionsLoad --> submissionList
  surveySubmissionsLoaded --> submissionList

  subgraph hooks
    useHydratedSurveySubmission
    useSurveySubmission
    useSurveySubmissions
  end

  useHydratedSurveySubmission --> useSurveySubmission
  useSurveySubmission --> submissionList
  useSurveySubmission --> submissionLoad
  useSurveySubmission --> submissionLoaded
  useSurveySubmission --> surveySubmissionUpdate
  useSurveySubmission --> surveySubmissionUpdated
  useSurveySubmissions --> submissionList
  useSurveySubmissions --> surveySubmissionsLoad
  useSurveySubmissions --> surveySubmissionsLoaded

  subgraph components
    SurveyOptionColumnType
    SurveyResponseColumnType
    SurveySubmittedColumnType
    SurveySubmissionPane
    SurveySubmissionsList
  end

  subgraph pages
    submissions.tsx
  end

  submissions.tsx --> useSurveySubmissions
  SurveySubmissionsList --> useSurveySubmission
  SurveySubmissionPane --> useHydratedSurveySubmission

  submissions.tsx --> SurveySubmissionsList
  SurveyOptionColumnType --> SurveySubmissionPane
  SurveySubmissionsList --> SurveySubmissionPane
  SurveyResponseColumnType --> SurveySubmissionPane
  SurveySubmittedColumnType --> SurveySubmissionPane

```

I do see the _hypothetical_ potential for an abstraction leak in `SurveyOptionColumnType` and friends. Those are loaded into `ViewDataTable`, which is used all over the place. If someone more familiar with this code can confirm that's not a risk here then the above flow chart is actually capturing the entire problem space in one neat little box.

Looks to me like this is a matter of grabbing `surveyId` out of `useRouter().query` and then passing it down through the params of the hooks and actions so that everywhere that needs it has it. Sound like a decent plan?
