### ISSUE TITLE
Page icon uses old logo

### ISSUE THREAD

**Issue by richardolsson** [zetkin/app.zetkin.org#2053]
## Description
The page icon "favicon" uses the old Zetkin logo. I think it should be replaced with the new Zetkin logo against a black background

## Steps to reproduce
1. Go to https://app.dev.zetkin.org/organize/1
2. Log in

### Expected Behaviour
The browser tab should display one of the new logos from https://zetkin.org/go/branding, most reasonably the single Z (without "zetkin" or "zetkin foundation".

### Actual Behaviour
The browser tab displays the old Zetkin logo.

## Screenshots
![image](https://github.com/zetkin/app.zetkin.org/assets/550212/fc676517-2492-41d6-8b39-0faa1afd2fd6)

**Comment by MattettaM** [comment]
Needs a designed icon since the variant I made which used the white version of the logo disappears if the user is using a light theme on their browser, and the logo was also slightly distorted.
![image](https://github.com/user-attachments/assets/cbd3b914-52e5-4497-9dfd-2f92647cbd08)
![image](https://github.com/user-attachments/assets/a968f418-219e-4378-bff3-68c26df09046)

**Comment by Bagera** [comment]
![favicon](https://github.com/user-attachments/assets/0866242f-399e-4094-9866-dba9438c8752)

Use this image
