### ISSUE TITLE
Use Prettier for Formatting 

### ISSUE THREAD

**Issue by djbusstop** [zetkin/app.zetkin.org#214]
### Description

Use Prettier for formatting, integrate with ESLint so it is checked in CI.

### Requirements
- [x]  ~~If file is formatted with Prettier, there should be no changes in a diff for a current file (where possible).~~
- [x]  Remove any formatting rules that Prettier would handle from ESLint.
- [x]  Use Prettier ESLint plugin and rules.
- [x]  Figure out and document how to get VS code formatting to do ESlint and Prettier formatting on save.
- [x]  2 Space indentation
- [x]  Add eslint next config to project and fix any errors that come up
- [x]  Disable ESlint rule: `@typescript-eslint/no-non-null-assertion` and remove line ignores from various files
- [x]  Disable ESlint rule: `react-hooks/exhaustive-deps`

Check this out for reference. We shouldn't implement this directly, but gives an idea what is needed: Check out this: https://gist.github.com/bradtraversy/aab26d1e8983d9f8d79be1a9ca894ab4#2-install-packages

### If possible:
- [ ] ESLint rule that orders alphabeltically in destructured objects
- [x] Find way to lint YAML files

**Comment by lowlandjuju** [comment]
I'm a fan of this issue :clap:

**Comment by richardolsson** [comment]
If you want to take a stab at it @lowlandjuju, feel free! 💯 

I have very little relevant experience, and I believe @djbusstop felt the same when we discussed this last. What's listed as "requirements" above is (as always, really) up for discussion if you have any other suggestions.

**Comment by lowlandjuju** [comment]
Suggest to remove eslint rule "react-hooks/exhaustive-deps" - it appears 14 times in an `/* eslint-disable...`

**Comment by richardolsson** [comment]
@lowlandjuju writes on Slack:

> I was struggling with the task of integrating prettier and meeting the requirement of:
> * "If file is formatted with Prettier, there should be no changes in a diff for a current file (where possible).
>
> And, well, it's not possible! I had to revisit Prettier's philosophy and realised that, of course it's not possible because Prettier deliberately doesn't allow configuration.
> See https://prettier.io/docs/en/option-philosophy.html
>
> The decision really is - we adopt Prettier's philosophy, or we stick with our self-managed eslint formatting solution.
>
> If we did adopt prettier, then I would suggest we keep prettier out of CI, so that the formatting changes can occur over the codebase gradually, file-by-file

I think this is valid, and part of why we want to move to Prettier is to get a more uniform formatting (which is not the same as, but does overlap, linting).

So my opinion is that we should adopt Prettier even though it means changing the format of a lot of code.

Where I disagree is on this: 

> If we did adopt prettier, then I would suggest we keep prettier out of CI, so that the formatting changes can occur over the codebase gradually, file-by-file

I think we should make a big commit that changes the formatting of everything in one go. I prefer to do that because there will be a single PR that we can review for what it is – purely changes to formatting. It will also be a single commit in the log that we can know to skip when we look at git history in the future (e.g. using `git blame --ignore-rev`). That's better, IMO, than reviewers having to distinguish formatting changes from substantial changes every time a commit touches an old file for the first time since the migration.

So, one big commit is my preference, but it should be done at a point in time where we can coordinate it so that it doesn't interfere with work too much, e.g. right after the release of R30, at the beginning of the R31 cycle.

For that reason (and just because we're running out of time for R30), I wanna postpone this until R31. But I'm curious to hear thoughts from others on the strategy.

**Comment by lowlandjuju** [comment]
I also am a fan of the prettier philosophy so agree there. Also im favour of a single big stylechange PR instead of piecemeal - I think I suggested piecemeal because I assumed that's what other people would want to do. 😄

**Comment by richardolsson** [comment]
Ok, so I couldn't help myself so I had a go at applying prettier just to see what would happen. This is about the level of complexity I can deal with on a Friday afternoon, so I thought why not. Here's what I did:

## Install dependencies
```bash
yarn add -D prettier eslint-config-prettier
```

## Remove style rules from eslint
We still want eslint for code quality stuff, just not for style. I made the changes in the patch below, but am very open to removing more rules if anyone wants to get rid of any.

```patch
diff --git a/.eslintrc.js b/.eslintrc.js
index 273916a..a4a1c59 100644
--- a/.eslintrc.js
+++ b/.eslintrc.js
@@ -5,8 +5,9 @@ module.exports = {
     es6: true,
   },
   parserOptions: { ecmaVersion: 8 }, // to enable features such as async/await
-  ignorePatterns: ['node_modules/*', '.next/*', '.out/*', '!.prettierrc.js', ], // We don't want to lint generated files nor node_modules, but we want to lint .prettierrc.js (ignored by default by eslint)
-  extends: ['eslint:recommended', 'plugin:react/recommended'],
+  // We don't want to lint generated files nor node_modules, but we want to lint .prettierrc.js (ignored by default by eslint)
+  ignorePatterns: ['node_modules/*', '.next/*', '.out/*', '!.prettierrc.js', ],
+  extends: ['prettier'],
   settings: { react: { version: 'detect' } },
   overrides: [
     // This configuration will apply only to TypeScript files
@@ -19,7 +20,6 @@ module.exports = {
         es6: true,
       },
       extends: [
-        'eslint:recommended',
         'plugin:@typescript-eslint/recommended', // TypeScript rules
         'plugin:react/recommended', // React rules
         'plugin:react-hooks/recommended', // React hooks rules
@@ -45,60 +45,21 @@ module.exports = {
           'interfaces': ['signature', 'method', 'constructor', 'field'],
         }],
 
-        'brace-style': ['error', 'stroustrup'],
-        'comma-dangle': ['error', 'always-multiline'],
-        'quotes': ['error', 'single', { 'allowTemplateLiterals': true, 'avoidEscape': true }],
-        'indent': ['error', 4],
         'jsx-a11y/anchor-is-valid': 'off',
-        'jsx-quotes': ['error', 'prefer-double'],
-        'keyword-spacing': ['error', {}],
         'no-console': 'error',
         'no-switch-statements/no-switch': 'error',
         'no-trailing-spaces': 'error',
-        'object-curly-spacing': ['error', 'always'],
-        'padding-line-between-statements': ['error',
-            // imports go together, but last import must be followed by newline
-            { blankLine: 'always', prev: 'import', next: '*' },
-            { blankLine: 'any', prev: 'import', next: 'import' },
-
-            { blankLine: 'always', prev: 'export', next: '*' },
-            { blankLine: 'always', prev: '*', next: 'export' },
-
-            { blankLine: 'always', prev: 'function', next: '*' },
-            { blankLine: 'always', prev: '*', next: 'function' },
-        ],
         'prefer-const': ['error', {}],
-        'react/jsx-closing-bracket-location': ['error', {
-            'nonEmpty': 'after-props',
-            'selfClosing': 'line-aligned',
-        }],
-        'react/jsx-closing-tag-location': 'error',
-        'react/jsx-curly-brace-presence': 'error',
-        'react/jsx-curly-spacing': ['error', {
-            'children': true,
-            'spacing': {
-                'objectLiterals': 'never',
-            },
-            'when': 'always',
-        }],
-        'react/jsx-equals-spacing': 'error',
         'react/jsx-handler-names': ['error', {
             'eventHandlerPrefix': 'on',
             'eventHandlerPropPrefix': 'on',
         }],
-        'react/jsx-indent': 'error',
-        'react/jsx-indent-props': 'error',
         'react/jsx-no-target-blank': 'error',
         'react/jsx-props-no-multi-spaces': 'error',
         'react/jsx-sort-props': ['error', {
           'ignoreCase': true,
           'reservedFirst': true,
         }],
-        'react/jsx-tag-spacing': ['error', {
-            'beforeClosing': 'never',
-            'beforeSelfClosing': 'allow',
-        }],
-        'react/jsx-wrap-multilines': 'error',
         'react/no-deprecated': 'error',
         'react/no-typos': 'error',
         'react/no-unknown-property': 'error',
@@ -117,7 +78,6 @@ module.exports = {
         }],
         'sort-keys': 'error',
         'sort-vars': 'error',
-        'space-before-blocks': ['error', 'always'],
       },
     },
   ],

```

## Apply prettier to all non-test files and verify
I don't want to touch the tests at first, because I want to be able to run them unmodified to make sure they still pass with the reformatted application code.
```bash
find src |grep -E "\.tsx?$" |grep -vE "spec\.tsx?$" |xargs yarn prettier --write
PLAYWRIGHT_WORKERS=1 yarn suite
```

## Apply prettier to previously excluded tests and verify
```bash
yarn prettier --write src playwright
PLAYWRIGHT_WORKERS=1 yarn suite
```

## Conclusion
It seems to have worked fine, produced working code and made for a huge patch: 😱 

```
288 files changed, 11803 insertions(+), 7982 deletions(-)
```
