### ISSUE TITLE
Calendar in WEEK mode shows 24 hours for every day

### ISSUE THREAD

**Issue by WULCAN** [zetkin/app.zetkin.org#2151]
## Description

The days where DST begins and ends are displayed with 24 hours in the WEEK-mode of an organization calendar, even though they in local time have 23 or 25 hours.

An event in central Europe scheduled between 2 AM and 3 AM on such a date is very likely to be interpreted differently by different users. That hour either does not exist in local time, or occurs twice in local time.

* https://en.wikipedia.org/wiki/Day
* https://en.wikipedia.org/wiki/Summer_time_in_Europe

## Steps to reproduce
1. Go to `/organize`
2. Open an organization
3. Open CALENDAR
4. Switch to WEEK mode
5. Go to week 43, including the last Sunday in October --- 2024-10-27

### Expected Behaviour

* either a calendar omitting 12 AM -- 3 AM from every day
* or a calendar omitting 12 AM -- 3 AM for Sunday
* or a calendar with 25 hours for Sunday
* or a calendar displaying which time zone is used

### Actual Behaviour

A calendar with 24 hours per day is displayed and no time zones are indicated.

## Screenshots (if you have any)

![image](https://github.com/user-attachments/assets/f7f19059-0cbf-47d1-8b8b-1a3fd27783e3)

**Comment by Jrende** [comment]
I will look at this, though I don't know any calendars that shows DST in the date view. Breaking new ground! 😀

**Comment by Jrende** [comment]
So, I spent some time coding and thinking about time zones (Did you know that there's a research station in Antarctica that changes 2 hours during dst? Now you know!)

I tried to show the hour in which DST changes. Winter time sunday has two 01:00, summertime just show a grey square for it.
![Screen Shot 2024-09-28 at 12 03 43](https://github.com/user-attachments/assets/754fff44-ea51-4267-bac5-4b5fcb027c8b)
![Screen Shot 2024-09-28 at 12 41 53](https://github.com/user-attachments/assets/2800ba13-8b5b-4eac-9aaf-0f3e1228e532)
Then I started to think about user experience rather than coding. What is the problem in this ticket? Is this actually what our user want to see?
I'm thinking a better solution would be to show a info text for the specific days, "This day DST goes into effect. Be aware!" or something similar.
@WULCAN, thoughts?
