### ISSUE TITLE
Importer phone problem when organization is misconfigured.

### ISSUE THREAD

**Issue by niklasva82** [zetkin/app.zetkin.org#2321]
When `country` is configured with lower-case country codes on an organization, phone number import encounters problems.

## Steps to reproduce
1. Configure an organization with country: "se"
2. Import a file with first name, last name, id and phone number

### Expected Behaviour
Either alert user to misconfiguration or at least throw an error so that devs can diagnose problem, or allow lowercase country codes.

### Actual Behaviour
Import is aborted due to unknown error. (because libphonenumber tries to use the lowercase country code and crashes, but doesn't log anything to the console.)

**Comment by troldmand** [comment]
Hey @niklasva82, is there any organization on this list with lower-case country code? 
![Screenshot 2024-11-19 at 10 33 26](https://github.com/user-attachments/assets/e5263d40-bb32-47d1-90b4-a2af1af705bb)

Because I don't know how to configure a new organization, so maybe one of them already can reproduce the error :)

**Comment by richardolsson** [comment]
You can change the language code of the organization back and forth by `PATCH` ing it (`/api/orgs/{ID}`), or you can just mock it in `useOrganization()` or whatever the name of the hook is.
