### ISSUE TITLE
Canvass assignments show up in wrong column under "Upcoming activities"

### ISSUE THREAD

**Issue by richardolsson** [zetkin/app.zetkin.org#2343]
## Description
"Canvass Assignments" is part of a new, pre-release feature. It's been rapidly developed over the past few months, and in that process, start/end dates were hardcoded on the frontend before they were implemented on the backend, and then never resolved. For that reasons, canvass assignments are always in the "Today" column.

## Steps to reproduce
The steps below need to be taken on an instance that has the environment variable `FEAT_AREAS=*` to enable the areas/canvass feature for all organizations on the instance. When you're running a local build, you need to set that environment variable in `.env.local`.

1. Go to https://app.dev.zetkin.org/organize/1 (if you're on localhost, don't forget about the `FEAT_AREAS` flag)
2. Create a new project
3. In the new project, create a canvass assignment
4. Set the start date of the canvass assignment to tomorrow's date
5. Go back to the project

### Expected Behaviour
In the today/tomorrow/also this week overview, the canvass assignment should be in the "tomorrow" column.

### Actual Behaviour
The assignment is in the today column. This is because the dates on the "activity" object is hardcoded to today's date.

## Screenshots (if you have any)
![image](https://github.com/user-attachments/assets/3b58fe88-568c-433a-b8a6-9d4b9d054f27)

**Comment by k-nut** [comment]
I gave this a shot in #2344. There were two things that I had issues with though:

- I had to make sure to have a local mongodb running and wired up properly using the `MONGODB_URL` environment variable. My guess is that this is only currently required since this is a beta feature?
- Your instructions say `4. Set the start date of the canvass assignment to tomorrow's date`. I assumed that I would be able to do this by clicking the `PLAN NOW` button on the canvass details page. That only gave me a 404 though since it seems like no `canvassassignments/[canvassAssID]/plan.tsx` route is registered yet? I worked around this by setting the date string manually in mongo.

I'd be happy to hear if I missed anything in the setup here.
