### ISSUE TITLE
Background color

### ISSUE THREAD

**Issue by richardolsson** [zetkin/app.zetkin.org#344]
The background color should be a very light shade of gray (`#F9F9F9`) according to designs, but is currently plain white. I think this must have happened when se removed the last remnants of Adobe Spectrum recently.

![image](https://user-images.githubusercontent.com/550212/128149909-6c261105-cefd-444c-9ca8-3ffd843fefc5.png)

**Comment by richardolsson** [comment]
I know not everyone is a fan of the gray background color. And in some contexts I actually think it doesn't look great, like here (where it's battling against the green):

![image](https://user-images.githubusercontent.com/550212/128594364-17336a24-3701-4187-a7e5-d7e8cc9ee052.png)

Maybe switching it around and putting the background color on the sidebar instead is nice?

![image](https://user-images.githubusercontent.com/550212/128594341-dd438c06-cbd5-4b39-9272-edc0784dce1b.png)

Note that in both of these screenshots I've changed the color of the Zetkin logo to Zetkin red which I think is nicer than the gray, and made it smaller to fit in it's white circle.

**Comment by omidhq** [comment]
I tried both options. Personal preference: the first one is nice because it makes the white cards stand out (first screenshot) but I agree with not fitting much when it's battling against green—not that bad though. The second option is nice too. I also tried a 3rd: a tiny bit of darker shade of gray `#F2F2F2` for the sidebar and the lighter `#F9F9F9` for the main background. 

Your thoughts? @richardolsson 
<img width="1355" alt="scc" src="https://user-images.githubusercontent.com/727082/130096590-a8c511a6-f1a5-4c80-ab43-0dfe156d13ed.png">

**Comment by GemCopeland** [comment]
@omidhq you're correct that the background is grey to make the white cards stand out more. I really think grey background is better than white for the main section.

I think a better solution could be to make the notification banners a bit more prominent by using a brighter colour complementary colour (#B8F7DF in this sketch) and a drop shadow.

![Notification](https://user-images.githubusercontent.com/2996847/130200420-e5ef2be7-54b3-4b9e-8a7d-11368fc1cbb6.png)

**Comment by richardolsson** [comment]
Awesome @GemCopeland! 🙌 

Let's proceed with this then, @omidhq. Please file a separate issue for tweaking the style of `Alert`.
