### ISSUE TITLE
Show many/percentage of how many have completed a Survey

### ISSUE THREAD

**Issue by synlic** [zetkin/app.zetkin.org#513]
### Description
You should be able to in the "Survey" app be able to see how many have responded to the survey - or in the case you've invited people - how many in percentages have responded. 

### Relevant Job Stories
Unknown

### Prerequisites
Unknown

### Requirements
Unknown

### Possible implementations
Unknown

### Design specifications
Unknown

**Comment by richardolsson** [comment]
I'm sorry you did not get any feedback on this issue @synlic. Based on my understanding of the description you have submitted, I believe this issue is fixed. It's possible on the survey page to see how many people have responded. It is not possible to see a percentage, but that's because there isn't really a "target group" for surveys so that percentage would rarely make sense.

I'm closing this as completed, but please comment or reopen if you feel like it's not fixed.
