### ISSUE TITLE
Organize code structure

### ISSUE THREAD

**Issue by ziggabyte** [zetkin/app.zetkin.org#788]
## Description
The code base for Gen 3 needs a bit of a tidy. 

This is a structure Ziggi suggested after a looking at it a bit, the post and discussion can be found here on slack: 
https://zetkin.slack.com/archives/CTL4L8V4P/p1654767269844889
![bild](https://user-images.githubusercontent.com/58265097/185106405-f44d3b13-569f-46ae-8ee1-e72b4d0a7ea3.png)

**Comment by ziggabyte** [comment]
In the discussion on Slack River's opinion was that this should happen in relation to a design audit - I guess so that the components we want to organize are actually the components that we want to use, and that the organization reflects the design system that @yusf will be creating. 
What are the feels on this? What do we want this task to contain - is it part of a design audit? What are the thoughts on the sketch I made before etc. @richardolsson and @Bagera should also be tagged i think :)

**Comment by richardolsson** [comment]
The ideas that i've started discussing in #793 might influence this, because they introduce some new categories of code (models, adapters and a separation into connected/dumb components).

**Comment by richardolsson** [comment]
I have a radical proposal, guided by decisions I made when I wrote the code for the Supporter App, which in turn was influenced by a number of Flutter tutorials, one of which referenced a segment of an "Uncle Bob" presentation that critiqued the prevalence of framework smell in source trees nowadays ([YouTube clip](https://youtu.be/NeXQEJNWO5w?t=438)). 

Basically, the top-level "components", "api", "hooks" and other folders like that tell us (roughly) what design patterns we use in the app, but nothing about what the app actually does. Instead, some people recommend a "features" folder, where each "feature" of the app has a directory with relevant GUI, API and model/logic code.

Some parts of a codebase are not strictly related to a single feature, so there needs to be some way to handle misc code like that as well. That includes our reusable GUI components, utilities, maybe some core framework logic etc.

Employing these principles might result in a tree that looks something like this:

* src
  * zui (our reusable GUI components)
  * utils
  * features
    * campaigns
      * api
      * hooks (or models or whatever)
      * components
    * tags
      * api
      * hooks (or models or whatever)
      * components
    * views
       * api
       * hooks
       * components
  * pages (for routing, as mandated by NEXT.js)

With this setup, code is grouped by _what it does_  rather than _what it is_, and different kinds of code (GUI, model etc) that relate to the same user-facing feature goes closely together.

I think this solves a problem that we have with our code base right now, which is that the `components` directory has amassed so many components, that we've had to start grouping them in sub-directories `components/forms` (which contain code that is related only by it all being forms) and `components/views` (which contains code for different aspects of the views feature).

I like it! What do you think? 😊

**Comment by ziggabyte** [comment]
> I like it! What do you think? 😊

I fkn love a radical idea and you know it!
This picks up on a lot of confusion I feel when I look at the structure today, which is mainly that I don't really feel a direct connection to what the pattern is that guides where something ends up. Where my suggestion gives a manicure to the existing order, this suggestion gives me much more energy and I'm excited to try it. 

Let's go!

**Comment by ziggabyte** [comment]
Let's do this thing! How do we do it? Do someone just make a branch and start moving files around or is there more steps? @richardolsson
